server:
  port: 8080
  
spring:
  application:
    name: Bootstrap Spring Boot
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html  