server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false
  
spring:
  application:
    name: Bootstrap Spring Boot
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    
joinfaces:
  faces:
    project-stage: development
#  primefaces:
#    theme: omega    